### 01 서울시 구별 CCTV 현황 분석

[학습목표]  

- 서울시 각 구별 CCTV수를 파악하고, 인구대비 CCTV 비율을 파악해서 순위 비교 
- 인구대비 CCTV의 평균치를 확인하고, CCTV가 과하게 부족한 구를 확인 
- pandas 사용법과 시각화(matplotlib) 사용법을 배운다.

#### 판다스 라이브러리

- 판다스 : python의 데어터 분석 및 조작을 위한 라이브러리로 
- 표(데이터프레임)형식 데이터를 다루는 강력한 기능 제공
- 엑셀, SQL, CSV 등의 데이터를 불러와 정리, 분석, 변환, 저장하는 기능 
- 데이터 분석에 필수적인 라이브러리다.


1. Pands 핵심 구조
- pandas에는 Series와 DataFrame 두가지 주요 데이터 구조가 있다

1.1 Series (1차원 데이터 처리시 사용)
- 단일 컬럼 형태의 데이터 구조를 가지고 있다 (시리즈로 컬럼단위 처리)
- 리스트(list)나 배열(array)과 유사하고 인덱스를 사용한다(인덱싱,슬라이싱 가능)

1.2 DataFrame (2차원 데이터 처리시 사용)
- 엑셀의 표와 같은 행(row)-열(column) 구조 
- 여러 개의 Series(컬럼)으로 구성된 것이다.


#### 1. series attribute(변수) 
- index : 인덱스 저장 (array)
- values : 값 저장 (array)
- dtype : 데이터 타입 저장 
- name : series object 이름 => 데이터프레임으로 가면 컬럼명으로 사용된다.

#### 2. Series 데이터 타입  
- index, value 다 array형식으로 저장
- array 형식 : numpy 저장 
    - 동일 데이터 타입만 저장 가능
    - 데이터 타입 세분화 된다. 
        - 정수,실수,문자열 등등 다 별도의 데이터 타입으로 있다.

In [16]:
# 예제 1 : Series 생성
import pandas as pd # 별칭 
# data에 들어갈수 있는 것 : 리스트, 딕셔너리, 배열 가능 
data = [1,2,3,4]
series = pd.Series(data)
print(series) 
print(series.index)
print(series.values)
print(type(series.values))
print(series.dtype)

series.name ='컬럼명'
print(series.name)

0    1
1    2
2    3
3    4
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[1 2 3 4]
<class 'numpy.ndarray'>
int64
컬럼명


In [9]:
# 2. 데이터프레임 생성
# 딕셔너리로 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Seoul', 'Busan', 'Incheon']
}
#print(data)
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   25    Seoul
1      Bob   30    Busan
2  Charlie   35  Incheon


In [11]:
# 특정 컬럼 선택 
# 컬럼들 확인 
print(df.columns)

Index(['Name', 'Age', 'City'], dtype='object')


In [13]:
print(df['Name'])
print(df['Age'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
0    25
1    30
2    35
Name: Age, dtype: int64


In [18]:
# DataFrame 주요 속성(attribute)  
# 1. columns : 컬럼들을 관리
# 2. index : 인덱스 관리
# 3. dtype : 컬럼별 데이터 타입 관리
# 4. shape : 데이터 구조 (행x열) 
print(df.columns)
print(df.index)
print(df.values)
print(type(df.values)) # array => numpy 전용 데이터 저장 방법
print(df.shape) # (3,3) tuple

Index(['Name', 'Age', 'City'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
[['Alice' 25 'Seoul']
 ['Bob' 30 'Busan']
 ['Charlie' 35 'Incheon']]
<class 'numpy.ndarray'>
(3, 3)


In [2]:
# CCTV 현황 데이터 읽기
# 파일 : data_collection\data\02 자료실\01. CCTV_in_Seoul.csv
# csv 읽기 함수 : pd.readcsv() => return DataFrame object
import pandas as pd 
import numpy as np

CCTV_Seoul = pd.read_csv(
    './data/01. CCTV_in_Seoul.csv', # 파일과 파일의 경로 지정
    encoding='utf-8'                     # 한글을 유니코드를 사용해서 읽기 
)
print(type(CCTV_Seoul))
# print(CCTV_Seoul)
# print(CCTV_Seoul.head()) # 상위 5개 데이터 확인
# print(CCTV_Seoul.tail())  # 하위 5개 데이터 확인
# CCTV_Seoul.head(10) # 상위 10개 행 데이터 추출 => DataFrame return 


<class 'pandas.core.frame.DataFrame'>


In [39]:
# CCTV_Seoul DataFrame 구조 확인
# 행정보 추출
# CCTV_Seoul.index : RangeIndex(start=0, stop=25, step=1) : 정수인덱스 
# 2. 컬럼들 추출
print(CCTV_Seoul.columns)
# 2.1 특정 컬럼 추출
print(CCTV_Seoul.columns[0])
print(CCTV_Seoul.columns[-1])
# 3. 구조 추출
print(CCTV_Seoul.shape) # (25,6) : 25행, 6개 컬럼
print(CCTV_Seoul.shape[0]) # 데이터 갯수 확인
print(CCTV_Seoul.shape[1]) # 컬럼의 갯수 확인


Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')
기관명
2016년
(25, 6)
25
6


In [51]:
# 수치 데이터의 기본 통계량
# CCTV_Seoul.head(2)
# CCTV_Seoul[['소계','2014년']]  # 컬럼 추출 => Series object => dtype
# CCTV_Seoul['기관명'].dtype => return : dtype('O') 문자열 

CCTV_Seoul.describe() # 통계량 구하는 메소드 /// std -> 분산 : 평균으로 부터 떨어져있는 정도


소계    2013년도 이전       2014년       2015년       2016년
count    25.000000    25.000000   25.000000   25.000000   25.000000
mean   1179.080000   764.760000  159.480000  205.200000  385.880000
std     556.728983   415.510257  104.132976  137.877059  182.479981
min     485.000000   238.000000   21.000000   30.000000   81.000000
25%     748.000000   464.000000   78.000000  103.000000  292.000000
50%    1015.000000   573.000000  142.000000  184.000000  377.000000
75%    1496.000000  1070.000000  218.000000  269.000000  467.000000
max    2780.000000  1843.000000  430.000000  584.000000  932.000000

In [52]:
# 데이터 전체 구조 확인 메소드 : info()
CCTV_Seoul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   기관명        25 non-null     object
 1   소계         25 non-null     int64 
 2   2013년도 이전  25 non-null     int64 
 3   2014년      25 non-null     int64 
 4   2015년      25 non-null     int64 
 5   2016년      25 non-null     int64 
dtypes: int64(5), object(1)
memory usage: 1.3+ KB


In [ ]:
# 컬럼명 수정 : 기관명 => 구별
# 메소드 : rename() 컬럼명 등을 수정할때 사용
gu = {
CCTV_Seoul.columns[0] : '구별'   
}
CCTV_Seoul.rename(
    columns =gu    
)# 이대로 하면 원본에 반영이 되지않는다.

In [56]:
CCTV_Seoul.head()

기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [59]:
# 컬럼명 변경
# 원본에 반영하는 방법 2가지
# 1. 다시 대입 : 기관명 => 구별 
CCTV_Seoul = CCTV_Seoul.rename(columns=gu)
CCTV_Seoul.columns
# 2. inplace= True : 구별 => 기관명 
gu = {
CCTV_Seoul.columns[0] : '기관명'   
}
CCTV_Seoul.rename(columns=gu, inplace= True)
CCTV_Seoul.columns
# 3. 기관명 = > 구별 변경
gu = {
CCTV_Seoul.columns[0] : '구별'   
}
CCTV_Seoul.rename(columns=gu, inplace= True)
CCTV_Seoul.columns 

Index(['구별', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

---
#### 인구현황 데이터 처리
---

In [ ]:
# 엑셀 파일 읽기 
# xls => xlrd module, xlsx : openpyxl module install
# conda install xlrd openpyxl
POP_seoul = pd.read_excel(
    './data/01. population_in_Seoul.xls' # 파일의 경로와 파일명
    ,header=2
    ,usecols ='B,D,G,J,N'
)
POP_seoul.head()

자치구           계        계.1       계.2   65세이상고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [4]:
POP_seoul.columns
# 컬럼명 변경
# ['자치구', '계', '계.1', '계.2','65세이상고령자']
# ['구별','인구수','한국인','외국인',''고령자']
columns = {
    POP_seoul.columns[0] : '구별'
    ,POP_seoul.columns[1] : '인구수'
    ,POP_seoul.columns[2] : '한국인'
    ,POP_seoul.columns[3] : '외국인'
    ,POP_seoul.columns[4] : '고령자'
}

POP_seoul.rename(
    columns=columns
    ,inplace =True
)

# 변경확인
POP_seoul.columns

Index(['구별', '인구수', '한국인', '외국인', '고령자'], dtype='object')

---
#### pandas 기본
---


In [ ]:
# Series 생성
data = [10,20,30,40,50] # list
index = ['a','b','c','d','e'] # 날짜 시간이 들어 갈 수 있다.=> 날짜 시간으로 데이터를 추출할수있게된다.
series = pd.Series(data=data, index=index)
print(series)
print(series['a'])

a    10
b    20
c    30
d    40
e    50
dtype: int64
10


In [ ]:
# Series 2
# key : index /values : data
data_index = {
    'a' : 10
    ,'b' : 20
    ,'c' : 30
    ,'d' : 40
    ,'e' : 50
}

series = pd.Series(data_index)
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [17]:
# Series 3
# 스칼라값(단일값)과 인덱스 리스트로 시리즈 생성
data = 5
index = ['a','b','c']
series = pd.Series(data=data, index=index)
series

a    5
b    5
c    5
dtype: int64

In [3]:
# Series 4
series = pd.Series(
    data =[1,2,3]
    , index=['a','b','c']
    , name='sample_series'
    , dtype='int8'
)
series

a    1
b    2
c    3
Name: sample_series, dtype: int8

In [7]:
# PDF in[10] : nan(not a number) => 결측치, 무한대의 의미가 있다.
import numpy as np
s = pd.Series([1,3,4,np.nan,6,8]) # data argument가 첫번째다.
s 

0    1.0
1    3.0
2    4.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [12]:
# pandas에서 날짜 시간 데이터 생성 : date_range()
import pandas as pd

dates = pd.date_range(
    '20250227' # 시작
    , periods=6
    , freq ='D' # D : 날짜 ME : 월
                 # dtype : 이거 나오면 무조건 ndarray 
)
dates

DatetimeIndex(['2025-02-27', '2025-02-28', '2025-03-01', '2025-03-02',
               '2025-03-03', '2025-03-04'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
print(np.arange(24))
print(np.arange(24).shape) # return => (24,) 1차원을 의미
print(np.arange(24).reshape(6,4)) # 6행 4열
print(np.random.randn(6,4)) # 6행 4열의 랜덤 행열

In [13]:
# DF 생성
# reshape 개많이씀 진짜 개많이 씀
import numpy as np

df = pd.DataFrame(
    np.arange(24).reshape(6,4) # data
    , index=dates
    , columns=['A','B','C','D']
)
df

A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23

In [22]:
print(df.index)
print(df.columns)
print(df.values)

DatetimeIndex(['2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31',
               '2025-06-30', '2025-07-31'],
              dtype='datetime64[ns]', freq='ME')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
# 데이터 구조, 정보 확인
df.info()


<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2025-02-28 to 2025-07-31
Freq: ME
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
 3   D       6 non-null      int64
dtypes: int64(4)
memory usage: 240.0 bytes


In [5]:
# 기본 통계
df.describe()


A          B          C          D
count   6.000000   6.000000   6.000000   6.000000
mean   10.000000  11.000000  12.000000  13.000000
std     7.483315   7.483315   7.483315   7.483315
min     0.000000   1.000000   2.000000   3.000000
25%     5.000000   6.000000   7.000000   8.000000
50%    10.000000  11.000000  12.000000  13.000000
75%    15.000000  16.000000  17.000000  18.000000
max    20.000000  21.000000  22.000000  23.000000

In [ ]:
# 데이터 처리
# 1. 정렬 (오름차순(ascending), 내림차순)
# B 컬럼의 값으로 내림차순 
# df.sort_values(by='컬럼명', ascending=True, ) # ascending = True 오름차순 , False 하면 내림차순 
df.sort_values(by='B', ascending=False ) # 원본은 정렬이 안되있다(반영되지 않았다).

A   B   C   D
2025-07-31  20  21  22  23
2025-06-30  16  17  18  19
2025-05-31  12  13  14  15
2025-04-30   8   9  10  11
2025-03-31   4   5   6   7
2025-02-28   0   1   2   3

In [14]:
# 시리즈에서 인덱싱 슬라이싱 : PDF in[22]
# df dataframe 에서 시리즈 추출 : 컬럼 한개는 시리즈다
df['A']

2025-02-27     0
2025-02-28     4
2025-03-01     8
2025-03-02    12
2025-03-03    16
2025-03-04    20
Freq: D, Name: A, dtype: int64

In [19]:
# in[23] : 데이터 프레임에서 슬라이싱
df[0:3]


A  B   C   D
2025-02-27  0  1   2   3
2025-02-28  4  5   6   7
2025-03-01  8  9  10  11

In [ ]:
df['20250227':'20250302'] # Named index 는 -1이 되지않는다. 문자열 그자체값이기에 -1이 되지않는다.
# Named index에서 주의 1 : end-1 안된다.
#                     2 : 슬라이싱의 return값은 DataFrame이다.

A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15

In [ ]:
# in[25]
# loc : NamedIndex로 접근 => 행단위 추출
df.loc['20250227']


A    0
B    1
C    2
D    3
Name: 2025-02-27 00:00:00, dtype: int64

In [ ]:
# iloc : integer index로 접근 => 행단위 추출
df.iloc[0]

A    0
B    1
C    2
D    3
Name: 2025-02-27 00:00:00, dtype: int64

In [ ]:
# loc, iloc 데이터 추출 : loc[], iloc[]
# 1. loc[행,열]
# 행,X면 행만 추출
# df.loc[start : end,['A','C']] : A, C 컬럼만 추출 => 팬시색인
df.loc[ : ,['A','C']]

A   C
2025-02-27   0   2
2025-02-28   4   6
2025-03-01   8  10
2025-03-02  12  14
2025-03-03  16  18
2025-03-04  20  22

In [24]:
# 날짜 인덱스로 접근 
df.loc['20250228':'20250302']

A   B   C   D
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15

In [ ]:
df.loc['20250228':'20250302',['A','D']] # => 슬라이싱 : 여러개 추출

A   D
2025-02-28   4   7
2025-03-01   8  11
2025-03-02  12  15

In [ ]:
# 팬시 색인 : 연속적이지 않은 값을 가져올때 사용
df.loc[['20250228','20250302'],['B','D']]

B   D
2025-02-28   5   7
2025-03-02  13  15

In [29]:
df

A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23

In [31]:
df.loc['20250228':'20250228',['A','B']]

A  B
2025-02-28  4  5

In [ ]:
print(df.loc['20250301','C'])   # named index
print(df.iloc[2,2])             # integer index 

10
10


In [39]:
df

A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23

In [45]:
# 03-01 행추출
print(df.loc['20250301']) # 인덱싱
print(df.loc['20250301',:]) # 슬라이싱
# C 컬럼 추출
print(df['C'])          # 컬럴단위 접근
print(df.loc[:,'C'])    # 행을 먼저 접근, 컬럼을 접근하는 방식
print(df)


A     8
B     9
C    10
D    11
Name: 2025-03-01 00:00:00, dtype: int64
A     8
B     9
C    10
D    11
Name: 2025-03-01 00:00:00, dtype: int64
2025-02-27     2
2025-02-28     6
2025-03-01    10
2025-03-02    14
2025-03-03    18
2025-03-04    22
Freq: D, Name: C, dtype: int64
2025-02-27     2
2025-02-28     6
2025-03-01    10
2025-03-02    14
2025-03-03    18
2025-03-04    22
Freq: D, Name: C, dtype: int64
             A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23


In [50]:
# IN[31] : integer index 사용한 슬라이싱
df.iloc[3:5,0:2]


A   B
2025-03-02  12  13
2025-03-03  16  17

In [49]:
# IN[32] integer index 사용한 팬시 색인 : 비연속인 데이터를 여러개 추출
print(df.iloc[[1,3,5],[0,2]])
print(df)

             A   C
2025-02-28   4   6
2025-03-02  12  14
2025-03-04  20  22
             A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23


In [51]:
# IN[33] : integer index
df.iloc[1:3,:]

A  B   C   D
2025-02-28  4  5   6   7
2025-03-01  8  9  10  11

In [57]:
# IN[34]
# print(df.iloc[:,'B':'C']) # iloc named index 사용 못함 에러
print(df)
print(df[['B','C']])
print(df.iloc[:,1:3])


             A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23
             B   C
2025-02-27   1   2
2025-02-28   5   6
2025-03-01   9  10
2025-03-02  13  14
2025-03-03  17  18
2025-03-04  21  22
             B   C
2025-02-27   1   2
2025-02-28   5   6
2025-03-01   9  10
2025-03-02  13  14
2025-03-03  17  18
2025-03-04  21  22


In [ ]:
# DataFrame에서 인덱싱(슬라이싱)
# 인덱싱, 슬라이싱, 팬시색인, 블린인덱싱
# 블린(조건) 인덱싱 : 조건에 맞는 데이터만 추출 
print(df) 
# print(df[조건]) : 조건에 맞는 행 추출
print(df[df['A'] < 5])
print(df['A'] < 5)


             A   B   C   D
2025-02-27   0   1   2   3
2025-02-28   4   5   6   7
2025-03-01   8   9  10  11
2025-03-02  12  13  14  15
2025-03-03  16  17  18  19
2025-03-04  20  21  22  23
            A  B  C  D
2025-02-27  0  1  2  3
2025-02-28  4  5  6  7
2025-02-27     True
2025-02-28     True
2025-03-01    False
2025-03-02    False
2025-03-03    False
2025-03-04    False
Freq: D, Name: A, dtype: bool


In [66]:
# df2 = df # 복사가 아니다
df2 = df.copy()
id(df2) is id(df)


False

In [67]:
# IN[38] : 데이터프레임에서 컬럼 추가
df2['E'] = ['one','one','two','three','four','three']
df2


A   B   C   D      E
2025-02-27   0   1   2   3    one
2025-02-28   4   5   6   7    one
2025-03-01   8   9  10  11    two
2025-03-02  12  13  14  15  three
2025-03-03  16  17  18  19   four
2025-03-04  20  21  22  23  three

In [68]:
# IN[39] : isin([여러개]) method : 블린인덱싱
# df['E'] Series object
df2['E'].isin(['two'])


2025-02-27    False
2025-02-28    False
2025-03-01     True
2025-03-02    False
2025-03-03    False
2025-03-04    False
Freq: D, Name: E, dtype: bool

In [ ]:
# IN[40]
df2[df2['E'].isin(['two','four'])]
# df[조건식] : True 행 추출 


A   B   C   D     E
2025-03-01   8   9  10  11   two
2025-03-03  16  17  18  19  four

---
#### date_range function
---

- 용도 : 일정 기간 동안의 날짜 범위를 생성하는데 사용, 주로 시계열 데이터
처리에 유용
- date_range(start, end, periods, freq, tz,,,,)


In [72]:
dates = pd.date_range('20250228', periods=7)
print(dates)

DatetimeIndex(['2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03',
               '2025-03-04', '2025-03-05', '2025-03-06'],
              dtype='datetime64[ns]', freq='D')


In [73]:
series = pd.Series(
    data = [1,2,3,4,5,6,7]
    ,index=dates    
)
print(series)
# 슬라이싱 : 연속된 데이터 추출
print(series['20250228':'20250302'])

2025-02-28    1
2025-03-01    2
2025-03-02    3
2025-03-03    4
2025-03-04    5
2025-03-05    6
2025-03-06    7
Freq: D, dtype: int64
2025-02-28    1
2025-03-01    2
2025-03-02    3
Freq: D, dtype: int64


In [ ]:
# 범위의 날짜로 생성 : 일단위 생성
date_range = pd.date_range(
    start='20250228'
    , end='20250618'
)
print(date_range)

DatetimeIndex(['2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03',
               '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07',
               '2025-03-08', '2025-03-09',
               ...
               '2025-06-09', '2025-06-10', '2025-06-11', '2025-06-12',
               '2025-06-13', '2025-06-14', '2025-06-15', '2025-06-16',
               '2025-06-17', '2025-06-18'],
              dtype='datetime64[ns]', length=111, freq='D')


In [78]:
# freq : 생성할 날짜 시간의 단위 지정
# 시간단위 생성
date_range = pd.date_range(
    start='20250228'
    , periods=10
    , freq='h'
)
print(date_range)

DatetimeIndex(['2025-02-28 00:00:00', '2025-02-28 01:00:00',
               '2025-02-28 02:00:00', '2025-02-28 03:00:00',
               '2025-02-28 04:00:00', '2025-02-28 05:00:00',
               '2025-02-28 06:00:00', '2025-02-28 07:00:00',
               '2025-02-28 08:00:00', '2025-02-28 09:00:00'],
              dtype='datetime64[ns]', freq='h')


In [ ]:
# freq= value
# value
# D : 일단위, B: 주말을 제외한 평일, h : 시간단위, min : 분단위, S : 초단위, ms : 밀리초
# W : 주단위, ME : 월단위, QE : 분기 단위, YE : 연단위

In [88]:
# 영업일 (B)
date_range = pd.date_range(
    start = '20250228'
    , periods=10
    , freq='QE'
)
print(date_range)

DatetimeIndex(['2025-03-31', '2025-06-30', '2025-09-30', '2025-12-31',
               '2026-03-31', '2026-06-30', '2026-09-30', '2026-12-31',
               '2027-03-31', '2027-06-30'],
              dtype='datetime64[ns]', freq='QE-DEC')


In [91]:
# 날짜 인덱스 생성
import numpy as np
import pandas as pd
from datetime import datetime
#    module            class

now = datetime.now()
print(now)

date_idx = pd.date_range(
    start=now
    , periods=5
)
print(date_idx)

2025-02-28 14:12:12.326108
DatetimeIndex(['2025-02-28 14:12:12.326108', '2025-03-01 14:12:12.326108',
               '2025-03-02 14:12:12.326108', '2025-03-03 14:12:12.326108',
               '2025-03-04 14:12:12.326108'],
              dtype='datetime64[ns]', freq='D')


---
#### 인덱싱, 슬라이싱, 팬시색인, 블린인덱싱
---

- 행이나 컬럼 추출 목적 
    - 1. 행 기준 추출 : loc[], iloc[]
    - 2. 컬럼 기준 추출 : ['컬럼명'], [['컬럼명','컬럼명']]
    - 3. 인덱싱 : 정수 인덱스, 네임드 인덱스 사용 방식이 있다

In [93]:
# 인덱싱, 슬라이싱
# 정수인덱스, 네임드인덱스
data = {
      'Name' : ['홍길동','고길동','마이꼴','둘리','희동']
    , 'Age' : [20,30,20,1000,2]
    , 'Addr' : ['울릉도','서울','서울','별','서울']
}
df = pd.DataFrame(data)
df


Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울

In [ ]:
# index는 key처럼 사용된다
# 홍길동, 20, 울릉도는 index 0으로 연결되있다.
print(df['Name'])
print(df['Age'])
print(df['Addr'])

0    홍길동
1    고길동
2    마이꼴
3     둘리
4     희동
Name: Name, dtype: object
0      20
1      30
2      20
3    1000
4       2
Name: Age, dtype: int64
0    울릉도
1     서울
2     서울
3      별
4     서울
Name: Addr, dtype: object


In [97]:
print(df.loc[0,:])
print(df.iloc[0,:])
print(df)

Name    홍길동
Age      20
Addr    울릉도
Name: 0, dtype: object
Name    홍길동
Age      20
Addr    울릉도
Name: 0, dtype: object
  Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울


In [98]:
print(df.index)

RangeIndex(start=0, stop=5, step=1)


In [99]:
df

Name   Age Addr
0  홍길동    20  울릉도
1  고길동    30   서울
2  마이꼴    20   서울
3   둘리  1000    별
4   희동     2   서울

In [100]:
# 특정 컬럼을 인덱스 영역으로 보내는 작업
# set_index(지정한 컬럼) 
df = df.set_index('Name')
df 

Age Addr
Name           
홍길동     20  울릉도
고길동     30   서울
마이꼴     20   서울
둘리    1000    별
희동       2   서울

In [101]:
# 홍길동의 데이터 추출(행추출)
df.loc['홍길동']

Age      20
Addr    울릉도
Name: 홍길동, dtype: object

In [ ]:
# 팬시 색인 : 홍길동 마이꼴 추출
df.loc[['홍길동','마이꼴']]

Age Addr
Name           
홍길동     20  울릉도
고길동     30   서울
마이꼴     20   서울
둘리    1000    별
희동       2   서울

In [103]:
# 블린 인덱싱
# 나이가 20 이상인 데이터 추출
df['Age'] >20 


Name
홍길동    False
고길동     True
마이꼴    False
둘리      True
희동     False
Name: Age, dtype: bool

In [104]:
df[df['Age']>20]

Age Addr
Name           
고길동     30   서울
둘리    1000    별

In [105]:
# 슬라이싱 : 고길동부터 둘리 행단위 추출
df.loc['고길동':'둘리']


Age Addr
Name           
고길동     30   서울
마이꼴     20   서울
둘리    1000    별

In [107]:
# 구분 컬럼 추가 
df['gubun'] =['가족','친구','회사','기타','가족']
df

Age Addr gubun
Name                 
홍길동     20  울릉도    가족
고길동     30   서울    친구
마이꼴     20   서울    회사
둘리    1000    별    기타
희동       2   서울    가족

In [ ]:
# 가족, 친구 검색
# 블린 인덱스
df[df['gubun'].isin(['가족','친구'])] # boolean return 

Age Addr gubun
Name                
홍길동    20  울릉도    가족
고길동    30   서울    친구
희동      2   서울    가족