---
#### 넘파이
---

1. 넘파이란
- 파이썬에서 수치 계산을 효율적으로 할 수 있도록 지원하는 라이브러리
- 다차원 배열 객체(ndarray) 를 제공
- 벡터, 행렬 연산과 같은 고속으로 수행할 수 있도록 최적화되어 있다.
- 과학 계산, 머신러닝(딥러닝), 데이터 분석등 다양한 분야에 사용

2. 특징
- 고속 연산 지원 : C언어로 구현되어 내부 연산이 빠르다
- 다차원 배열 지원
- 브로드캐스팅 지원 : 서로 다른 크기의 배열 간 연산을 가능 
- 다양한 수학 함수 지원 : 선형대수, 통계, 랜덤 샘플링 등의 다양한 함수 지원
- python 리스트보다 메모리 효율적 사용


In [1]:
# 3. 넘파이 기본 사용법
# 설치 : pip(conda) install numpy
import numpy as np


In [2]:
# 4. 주요 기능 및 예제
# 4.1 배열 생성(np.array(리스트, 튜플))
# 1차원 배열 생성
arr1 = np.array([1,2,3,4,5])
# 2차원 배열 생성 
arr2 = np.array([
    [1,2,3]
    ,[4,5,6]
])
# 3차원 배열 생성
arr3 = np.array([[
    [1,2]
    ,[3,4]
    ,[5,6]
    ,[7,8]
]])
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [17]:
# ndarray object attribute
print('배열의 차원 :', arr2.ndim)
print('배열의 크기 :', arr3.shape)
print('배열의 원소 개수 : ', arr2.size)
print('배열의 데이터 타입 : ', arr2.dtype) # ndarray 는 동일타입만 저장할 수 있다.

배열의 차원 : 2
배열의 크기 : (1, 4, 2)
배열의 원소 개수 :  6
배열의 데이터 타입 :  int64


In [25]:
# 4.3 특정값을 갖는 배열 생성
# 0값을 갖는 배열 : np.zeros((행,열))
zeros = np.zeros((3,3))
print(zeros)
# 1값을 갖는 배열 : np.ones((행,열))
ones_=np.ones((2,4))
print(ones_)
# 특정값으로 채운 배열 : np.full((행,열),특정값)
full=np.full((2,2),5)
print(full)
# 연속된 숫자로 채운 배열 : np.arrange(start, end-1, step)
arange_arr=np.arange(1,10,2)
print(arange_arr)
# np.linspace(start, end, count) : 균등한 간격으로 생성
lin_arr=np.linspace(0,100,5) # 0~100 사이에서 5개 값으로 생성
print(lin_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5]
 [5 5]]
[1 3 5 7 9]
[  0.  25.  50.  75. 100.]


In [ ]:
# 4.4 난수 배열 (ndarray) 생성
# numpy의 random 모듈을 사용하면 다양한 난수 배열을 생성할 수 있다.
# np.random.rand(행,열) : 0~1사이의 난수를 가진 배열 생성 
np.random.seed(42) # 42 => 아무의미 없다 그냥 씀 숫자 암거나 넣어도 됨
rand_arr=np.random.rand(3,4)
print(rand_arr)
# 정규분포를 따르는 난수 배열 생성 : np.random.randn(행, 열)
randn_arr=np.random.rand(2,2)
print(randn_arr)
# 특정 범위의 정수 난수 배열 생성 : np.random.randint(start, end, [(행,열)])
randint_arr=np.random.randint(1,4,(2,4))
print(randint_arr)


[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
[[0.83244264 0.21233911]
 [0.18182497 0.18340451]]
[[2 2 1 1]
 [1 3 3 3]]


In [48]:
# 4.5 배열 연산(더하기,빼기,곱셉,나눗셈,제곱)
a_vector=np.array([1,2])
b_vector=np.array([3,4])

print('덧셈 : ', a_vector+b_vector)
print('뺄셈 : ', a_vector-b_vector)
print('곱셉 : ', a_vector*b_vector)
print('제곱 : ', a_vector**b_vector)

덧셈 :  [4 6]
뺄셈 :  [-2 -2]
곱셉 :  [3 8]
제곱 :  [ 1 16]


In [57]:
# 배열 인덱싱 및 슬라이싱
arr=np.array([
    [1,2,3]
    ,[4,5,6]
    ,[7,8,9]
])
# arr.shape
# 특정 요소 접근 : 인덱싱 => 단일값 추출
print('첫번째 행, 두번째 열 : ', arr[0][1]) # arr[행][열]
print('첫번째 행, 두번째 열 : ', arr[0,1]) # arr[행,열]
# 특정 행 전체 슬라이싱 
print('첫번째 행 : ', arr[0])
print('첫번째 행 : ', arr[0,:]) # arr[행, 열자리(start:end)]
# 특정 열 슬라이싱
print('두번째 열 : ', arr[:,1])
# 부분 배열 가져오기
print('2x2 부분 배열 : ', arr[1:3,1:3]) # arr[1:2, 1:2]

첫번째 행, 두번째 열 :  2
첫번째 행, 두번째 열 :  2
첫번째 행 :  [1 2 3]
첫번째 행 :  [1 2 3]
두번째 열 :  [2 5 8]
2x2 부분 배열 :  [[5 6]
 [8 9]]


In [62]:
# 4.7 선호대수 연산
# X : 데이터, W: 가중치
# dot product : 
# 선형변환(Linear Transformation) : 주어진 벡터 데이터를 다른 차원으로 변환하거나 
# 특정 방향으로 확장/축소하는 역할


X = np.array([
    [1,2]
    ,[3,4]
])
W = np.array([
    [1,1]
    ,[2,2]
])

# 점곱
# 주어진 데이터(x)를 가중치(W)로 선형변환 한 것이다.

dot_prod=np.dot(X,W)
print('행열 곱 :', dot_prod)





행열 곱 : [[ 5  5]
 [11 11]]


In [ ]:
# 전치 행렬 : transpose
# X,X.T, X.transpose()
a=np.array([1,2,3])
print(a.shape)
b=np.array([4,5,6])
print(b.shape)

print(np.dot(a.T,b))
print(np.dot(a,b)) # numpy에서 자동 transpose해준다 



(3,)
(3,)
32
32


In [ ]:
a=np.array([ # 2x3
    [1,2,3]
    ,[4,5,6]
])
print(a.shape)
b=np.array([4,5,6]) #3x1
print(b.shape)

# print(np.dot(a.T,b)) => 3x2로 바뀜 error
print(np.dot(a,b)) # numpy에서 자동 transpose해준다 

(2, 3)
(3,)
[32 77]


In [ ]:
# 역행렬
# 역행렬 존재하는 조건
# 1. 정사각 행렬(Square Matrix) (n X n)
# 2. 행렬식이 0이 아니어야 한다
#    행렬식이 0이면, 역행렬이 존재하지 않고, 이러한 행렬을 특이행렬(Singular Matrix)
# 행렬식 : 정사각 행렬의 스칼라(단일값)값을 의미한다. 
# 특정 행렬(데이터)이 선형변환에서 공간을 얼마나 변형시키는지를 나타내는 값
